### ISSUE TITLE
Mise à jour et gestion de version

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#11]
En tant que **administrateur**, 
je souhaite **pouvoir mettre à jour et connaître la version de l'extension**
afin de **faciliter la maintenance**

**Comment by Gaetanbrl** [comment]
La version est modifiable dans le fichier php de l'extension.
Pour cela, modifier le champ "Version" dans les commentaire en en-tête du plugin : 
```
/*
Plugin Name: Map Store Location

Description: A plugin to display geographic data in a map.
Version: 1.0.0
Author: JDev
License: GPLv3 or later
Domain Path: /languages
*/
```

Les informations d'en-tête sont affichées ensuite dans la partie "extentions" de wordpress pour le plugin concerné :

![image](https://user-images.githubusercontent.com/16317988/70894992-611a1c00-1fee-11ea-90ef-1019b8540618.png)

**Comment by Gaetanbrl** [comment]
Lors d'une mise  jour du plugin sur le dépôt principal des extensions wordpress, les personnes qui ont installées le plugins sont notifiées de la mise à jour.

Ils peuvent procéder à cette mise à jour :
- Manuellement en remplaçant le répertoire /sitewordpress/wp-content/plugin/WP-map-store-locator par la mise à jour. Les données en base seront restituées, sauf si les options ont changées de nom.
- Automatiquement via l'interface d'administration wordpress page "plugins".
