### ISSUE TITLE
Internationnalisation

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#12]
En tant que **administrateur**,
je souhaite **pouvoir choisir la langue affichée**
afin de **faciliter la lisibilité**

La description de l'extension doit être en Anglais et en Français a minima

**Comment by Gaetanbrl** [comment]
Le fichier de traduction a été généré avec le plugin [loco-translate](https://fr.wordpress.org/plugins/loco-translate/).

Ce plugin permet de suivre l'avancement d'une traduction et de créer les fichiers de traduction de base pour plusieurs langues sans faire de code.

Ce plugin n'est pas a installer pour les utilisateurs mais que pour les développeurs qui créent les traductions. Le plugin WP-map-store-locator reste totalement indépendant.

**Comment by Gaetanbrl** [comment]
Étapes à suivre pour la traduction centralisée d'un plugin et des widgets qui en dépendent :

1. Définir un "text domain" et appeler les fichiers de traduction pour le plugin via la fonction : 
`load_plugin_textdomain( 'WP-map-store-locator', false, 'WP-map-store-locator/languages/' );`

2. Pour chaque chaîne de texte à traduire, utiliser une syntaxe du type :
`__('ma chaîne', 'text_domain')`

Ce qui donne : 
 `__('Welcome', 'WP-map-store-locator')` pour notre domaine de texte **WP-map-store-locator**.

3. Installer une extension de traduction dans wordpress type loco-translate.
4. Créer via l'extension les fichiers .mo et .po. Les traductions se feront au sein de l'interface du plugin [loco-translate](https://fr.wordpress.org/plugins/loco-translate/).

![image](https://user-images.githubusercontent.com/16317988/70921986-9857ef80-2025-11ea-9149-338fbfccc1eb.png)


 
![image](https://user-images.githubusercontent.com/16317988/70922020-a6a60b80-2025-11ea-841b-e62d88fea4e8.png)

5. En cas de nouvelle chaîne à traduire dans le code du plugin ou du widget, il faudra synchroniser le plugin loco-translate.

![image](https://user-images.githubusercontent.com/16317988/70922108-d0f7c900-2025-11ea-9841-f04ebb27d155.png)

6. Dans l'en-tête du fichier principal du plugin à traduire, insérer les champs : 
```
<?php
/*
Domain Path: /languages
Text Domain: WP-map-store-locator
*/
```
Où le domain path permet de préciser la localisation des fichiers de traduction.

7. Sauvegarder à chaque modification avec le plugin

8. Observer les traductions dans le fichier WP-map-store-location.po du type :

```
#: classes/admin/Admin.php:55
msgid "Save"
msgstr "Enregistrer"

#: classes/admin/Admin.php:69
msgid "Map options"
msgstr "Options de la carte"
```
