### ISSUE TITLE
[ Administration ] Nom sur la gauche

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#16]
![image](https://user-images.githubusercontent.com/11499415/71156177-be58dc00-223f-11ea-9f87-8257b6ab42c2.png)

Voir pour changer le nom pour comprendre que c'est map store locator

**Comment by Gaetanbrl** [comment]
Modification du nom MSL par "Map Store Locator".

Possibilité de modifier le nom selon la lange via les fichiers de traduction (fichiers .po et .mo).

![image](https://user-images.githubusercontent.com/16317988/71169820-23b9c680-225a-11ea-91d6-4d60ac92b1d5.png)
