### ISSUE TITLE
[ Administration ]  Visualisation des Symboles

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#18]
![image](https://user-images.githubusercontent.com/11499415/71156459-5951b600-2240-11ea-884c-5c4b2856055a.png)

Est-ce que c'est possible de prévisualiser les images des symboles ?

**Comment by pierrejego** [comment]
Et ajouter que c'est soit ce format soit une URL

**Comment by pierrejego** [comment]
Et pareil pour l'icône en bas
![image](https://user-images.githubusercontent.com/11499415/71156710-d11fe080-2240-11ea-80a3-43fe7831a7cb.png)

**Comment by Gaetanbrl** [comment]
Modification en cours : 

Ajout d'un aperçu pour les symboles utilisés et description du format à utiliser en tête de section.

![image](https://user-images.githubusercontent.com/16317988/71168494-2109a200-2257-11ea-9ca2-0a563a9ff532.png)

**Comment by Gaetanbrl** [comment]
Fix by [6693a30 ](https://github.com/jdev-org/WP-map-store-locator/commit/6693a30683667e451d5f38ad7c1a90c11a305176)
