### ISSUE TITLE
[ Recherche ] Texte dans la recherche

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#19]
![image](https://user-images.githubusercontent.com/11499415/71157143-b437dd00-2241-11ea-9aa8-3c8fb92f22c1.png)

Ce n'est pas le bon dans le texte dans le recherche ( et si possible internationalisé)

**Comment by Gaetanbrl** [comment]
Modification déjà réalisée mais pas push. Autant pour moi...

**Comment by Gaetanbrl** [comment]
Fix by commit [18b6b3 ](https://github.com/jdev-org/WP-map-store-locator/commit/18b6b3b86864c756d2807ea40a2fa27f53cbb9e0)
