### ISSUE TITLE
Configuration via une page d'administration

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#2]
La page d'administration doit permettre de choisir l'url d'appel aux données JSON

**Comment by Gaetanbrl** [comment]
L'administrateur peut modifier les options suivantes : 

- [x] Centrage par défaut de la carte (ex : coordonnées du vendeur principal)

- [x] Niveau de zoom par défaut de la carte

- [x] Page à ouvrir lors du clique sur le widget en mode simplifié (voir options du widget)

- [x] Titre à insérer dans la popup

- [x] Text à insérer dans la popup

- [x] Contenu HTML à insérer dans la popup (remplace le contenu par défaut)

- [x] Url des données (JSON / GeoJSON)

- [x] Taille du pictogramme (paramètre scale OpenLayers de 0 à 1)

- [x] Types (attributs à retrouver dans les propriétés)

- [x] Pictogramme par type (source / URL du pictogramme selon OpenLayers)

**Comment by Gaetanbrl** [comment]
La taille des pictogrammes pour chaque type n'est pas paramétrable.
