### ISSUE TITLE
Widget et positionnement

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#3]
Le widget créé doit pouvoir être placé dans n'importe quel emplacement d'une page.

L'extension doit contenir deux widgets. Un petit widget, qui lorsqu'on clique dessus ouvre le grand widget.

Exemple, un widget en bas de pas  sur un tiers de l'écran et trop petit pour voir correctement le résultat d'une recherche. Il serait donc intéressant de pouvoir ouvrir une page définit dans l'administration lors du clic sur ce "petit widget".

**Comment by Gaetanbrl** [comment]
Problème lors des tests d'intégration du même widget à deux endroit.

**Comment by Gaetanbrl** [comment]
Piste envisagée : intégrer un shortcode.
Avec un shortcode, les deux cartes disparraissent.

Le shortcode nécessite de placer l'appel du template de carte (HTML) dans une fonction.
Cette fonction doit générer un ID unique pour la div parente de la carte.
L'ID unique généré via PHP est ensuite affecté dans le paramètre "target" de la carte.

Cette solution fonctionne avec une seule carte... mais n'affichent pas non plus les deux sur une page et dans le footer.

**Comment by Gaetanbrl** [comment]
L'ajout d'un widget supplémentaire peut être envisagé mais ajoute une gestion de widget supplémentaire pour l'administrateur :
- Un wdiget pour le footer : `overview map widget`
- Un widget pour la recherche et l'affichage d'informations : search map widget

Ces widget, liés au plugin, partageront donc les mêmes options du plugin.
L'avantage, est que le widget dans la page peut avoir des options différentes du widget contenu dans le footer.

**Comment by Gaetanbrl** [comment]
Le widget peut être placé via un shortcode ou directement via l'interface de gestion d'emplacement des widget.
Le shortcode admet les options suivantes : 

- **map** (facultatif) : prend la valeur "simple" ou rien. Si défini, enlève la recherche, l'infobulle et les données. N'affichera que le point principale du vendeur. Au clic, la page définie dans le menu d'administration du plugin s'ouvrira. Si non défini, la carte s'affiche en mode complet.

- **height** (conseillé mais non obligatoire) : prend la valeur en px, em ou % pour définir la hauteur. Si non défini, la hauteur sera de `12em` par défaut.

- **width** (facultatif) : prend la valeur en px, em ou % pour définir la largeur. Attention aux effets de visualisation avec des terminaux mobiles. Si non défini, la valeur sera de `auto` par défaut.

L'utilisation du shortcode peut se réaliser en insérant cette syntaxe dans une page, un article, etc. :
`[msl map="simple" height:500px width:100%]`

Ces paramètres sont les mêmes que défini dans l'interface de gestion du widget : 
![image](https://user-images.githubusercontent.com/16317988/70923075-92fba480-2027-11ea-9936-cf6afb81d681.png)


Ces éléments permettent de gérer plusieurs cartes à des endroits différents sur le site wordpress.
