### ISSUE TITLE
Point du vendeur principal

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#6]
Via l'administration il doit être possible de positionner un point sur la carte, avec un niveau de zoom, et une image. 
Ce point correspond au vendeur principal et devra être afficher au chargement de l'extension.

Lors du cliques sur cette image, des informations pourront être affichées sous forme de pop-in

**Comment by Gaetanbrl** [comment]
Les options dans le volet d'administration du plugin permettent de définir un point, un picto et le niveau de zoom sur ce point.

Lors du clique sur cette image, l'utilisateur ouvre la page "contact" qui affiche une carte en mode "avancée".
Cette carte permet d'ouvrir une popup contenant des informations (paramétrées dans l'administration du plugin) : 
- Un titre
- Un texte
- Un contenu HTML chargé en tant que "contenu" et qui remplace entièrement le texte de la popup. Cette option permet de personnaliser la popup entièrement (image, lien, etc.).
