### ISSUE TITLE
Démonstrations

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#7]
En tant que **financeur**,
je souhaite **voir les évolutions des développements au fur et à mesure**
afin de **planifier son installation ou ses nouvelles évolutions**

Cette extension doit pouvoir être testé à tout moment. Il faut la déployer sur un environnement de qualification avant de la déployer sur l'environnement de pré-production.
Il faudrait faire une démo par semaine à la distillerie.

**Comment by Gaetanbrl** [comment]
La démonstration est disponible sur : 
[https://jdev.fr/wordpress](https://jdev.fr/wordpress)
