### ISSUE TITLE
Disponibilité de l'extension

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#8]
En tant qu'**admnistrateur WP**,
je souhaite **pouvoir trouver l'extension sur le store**
afin de **pouvoir l'installer**

Une fois la première version réalisée, cette extension doit être disponible à partir de la gestion d'extension de WP et hébergé sur les serveurs de WP

Il faut aussi mettre un lien pour permettre de connaître les développeurs et indiqué que l'on peut faire des développements spécifiques sur demande.

**Comment by Gaetanbrl** [comment]
Voici les étapes à suivre pour déposer un plugin dans le dépôt distant SVN général de Wordpress (store).
Source  : [ici](https://fr.wordpress.org/plugins/developers/).

1. Disposer d'un compte Wordpress.
2. Respecter la ligne de [conduite](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/).
3. Proposer un l'extension en vue d'une revue "manuelle" sur [cette page](https://fr.wordpress.org/plugins/developers/add/).
4. Récupérer au dépôt SVN l'accès fourni à la validation de l'étape de revue du plugin.
5. Déposer le plugin sur le dépôt.

**Comment by pierrejego** [comment]
Ok , j'ai créé le compte, 
Je fais une petite review et je fait le dépôt de l'extension

**Comment by pierrejego** [comment]
Code déposé, en attente de retour
