### ISSUE TITLE
Résultat de recherche

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/WP-map-store-locator#9]
En tant qu'**utilisateur**,
je souhaite **voir les informations des revendeurs le plus proche**
afin de **pouvoir les appeler ou m'y rendre**

Après une recherche d'adresse, les n revendeurs (configurable dans l'administration) les plus proches doivent être visible sur la carte.
Avec des symbologies différentes en fonction de leur catégorie (Caviste, Bar à Coktail, Restaurants), les informations détaillées du revendeurs le plus proches doivent s'afficher. 

Et pourquoi pas un carrousel pour afficher les autres revendeurs, en modifiant le placement sur la carte au fur et à mesure des changements

**Comment by Gaetanbrl** [comment]
**Etat actuel :**
> Après une recherche d'adresse, les n revendeurs (configurable dans l'administration) les plus proches doivent être visible sur la carte.

Par défaut la couche des revendeurs, détaillants n'est pas visible. Il faudra réaliser une première recherche pour afficher cette couche de façon persistante. Seul un rechargement de la page permettra de cacher ces données.

Une popup s'ouvrira sur le revendeur [le plus proche](https://github.com/jdev-org/WP-map-store-locator/blob/restructure/classes/widgets/Msl.php#L491).

> Avec des symbologies différentes en fonction de leur catégorie (Caviste, Bar à Coktail, Restaurants), les informations détaillées du revendeurs le plus proches doivent s'afficher.

Les symbologies sont bien différentes selon le type défini dans le volet d'administration du plugin. La symbologie (pictogramme) et est définir dans ce même volet d'administration du plugin. Ces informations seront affichés après une première recherche.

**Comment by Gaetanbrl** [comment]
> Et pourquoi pas un carrousel pour afficher les autres revendeurs, en modifiant le placement sur la carte au fur et à mesure des changements

Ce type d'interface est possible mais devra être réalisé avec la version jQuery par défaut et sans librairies externes (Bootstrap) sous peine de créer des effets de bord avec le thème chargé, **sauf tests concluant**.
